# Example of a basic REST API call 
#https://reqres.in/api/users

# OPTION REST api request to a WordPress site
# OPTIONS https://websitesupport247.com/wp-json/wp/v2/posts

# The Head section is not normally seen by us humans, but instead used by the client to handle the return data
HEAD  https://websitesupport247.com/wp-json/wp/v2/posts
